### PR TITLE
Load local files

### PR DESCRIPTION
**Pull request by dgomezferro**
This is hacked together as I'm no frontend dev, hopefully I didn't break anything.

### CODE REVIEW

**Comment by dgomezferro** [comment]
Here it is in action: https://dgomezferro.github.io/tla-web

**Comment by ajdavis** [comment]
This doesn't seem to update the contents of the "Spec" tab, I still see the default TwoPhase spec in there after using the "load file" feature.

**Comment by will62794** [comment]
Ported and pushed these changes in 15229e7. 

Note that copying spec/trace links won't really work if you load specs from a local file, since there is no global URL to load a spec from. Not a big issue, but just something to be aware of.

**Comment by will62794** [comment]
> This doesn't seem to update the contents of the "Spec" tab, I still see the default TwoPhase spec in there after using the "load file" feature.

@ajdavis Not sure if it is what you encountered, but sometimes you need to place your cursor into the code editor box in order for text changes to appear after a re-load. I will eventually smooth out this UI quirk.

**Comment by ajdavis** [comment]
Ah, that's what I'm seeing, correct.

**Comment by ajdavis** [comment]
But additionally, bug A:

1. Load spec from file
2. Change the contents of the file
3. Without refreshing the page, load spec from file again

Expected: the contents of the spec in tla-web are updated with the new file contents.

Actual: the contents of the spec in tla-web are unchanged.

Bug B:

1. Load spec from file
2. Change the contents of the spec in tla-web
3. Without refreshing the page, load spec from file again

Expected: file contents overwrite changes I made in tla-web.

Actual: the contents of the spec in tla-web are unchanged.

**Pull request closed without merging**
